/**
 * Sync public Buzz communities from https://buzz.directory/ into
 * src/data/marketplace-communities.generated.ts
 *
 *   npm run sync:directory
 *   npm run sync:directory -- --dry-run
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  hostFromRelayUrl,
  listingHasNextPage,
  mapDirectoryCategory,
  marketplaceIdFromDirectorySlug,
  parseBuzzCommunityRelay,
  parseBuzzDirectory,
  type ListedCommunity,
  type ResolvedCommunity,
} from "./lib/buzz-directory.ts";
import {
  inviteTokenFromJoinUrl,
  shouldFallbackExpiredPublicInvite,
} from "./lib/buzz-invite.ts";

type AccessMode = "public" | "invite";

type MarketplaceCommunity = {
  id: string;
  name: string;
  slug: string;
  blurb: string;
  tags: string[];
  access: AccessMode;
  joinUrl: string;
  host?: string;
  featuredRank?: number;
  listedAt: string;
  source?: "buzzftw" | "external" | "curated";
  accent?: string;
};

const UA =
  "buzzftw-directory-sync/1.0 (+https://github.com/radiofrequency/buzzftw)";
const DIRECTORY_ORIGIN = "https://buzz.directory";
const TIMEOUT_MS = 15_000;
const DETAIL_CONCURRENCY = 2;
const DETAIL_GAP_MS = 150;

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_PATH = path.join(
  ROOT,
  "src/data/marketplace-communities.generated.ts",
);

type Args = {
  dryRun: boolean;
  outPath: string;
};

function parseArgs(argv: string[]): Args {
  const dryRun = argv.includes("--dry-run");
  const outIdx = argv.indexOf("--out");
  const outPath =
    outIdx >= 0 && argv[outIdx + 1] ? path.resolve(argv[outIdx + 1]) : GENERATED_PATH;
  return { dryRun, outPath };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: {
      "User-Agent": UA,
      Accept: "text/html,application/xhtml+xml",
    },
    redirect: "follow",
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (!res.ok) {
    throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
  }
  return await res.text();
}

async function mapPool<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const index = next++;
      out[index] = await fn(items[index], index);
    }
  }
  const n = Math.min(Math.max(1, limit), items.length || 1);
  await Promise.all(Array.from({ length: n }, () => worker()));
  return out;
}

async function fetchDirectoryListings(): Promise<ListedCommunity[]> {
  const bySlug = new Map<string, ListedCommunity>();
  let page = 1;
  while (page <= 30) {
    const url =
      page === 1
        ? `${DIRECTORY_ORIGIN}/communities`
        : `${DIRECTORY_ORIGIN}/communities?page=${page}`;
    const html = await fetchText(url);
    const listed = parseBuzzDirectory(html);
    for (const row of listed) {
      if (!bySlug.has(row.directorySlug)) bySlug.set(row.directorySlug, row);
    }
    if (!listingHasNextPage(html, page)) break;
    page += 1;
    await sleep(DETAIL_GAP_MS);
  }
  return [...bySlug.values()];
}

function readGenerated(filePath: string): MarketplaceCommunity[] {
  if (!fs.existsSync(filePath)) return [];
  const text = fs.readFileSync(filePath, "utf8");
  const start = text.indexOf("= [");
  const end = text.lastIndexOf("]");
  if (start < 0 || end < 0) {
    throw new Error(`Could not find community array in ${filePath}`);
  }
  return JSON.parse(text.slice(start + 2, end + 1)) as MarketplaceCommunity[];
}

function serializeGenerated(rows: MarketplaceCommunity[]): string {
  const json = JSON.stringify(rows, null, 2);
  return `/**
 * Generated by \`npm run sync:directory\`. Do not edit by hand.
 * Editorial featuredRank / accent overrides live in marketplace-communities.ts.
 */
import type { MarketplaceCommunity } from "./marketplace-communities";

export const DIRECTORY_COMMUNITIES: MarketplaceCommunity[] = ${json};
`;
}

function findExisting(
  row: ResolvedCommunity,
  host: string,
  existing: MarketplaceCommunity[],
): MarketplaceCommunity | undefined {
  const short = marketplaceIdFromDirectorySlug(row.directorySlug);
  return existing.find(
    (c) =>
      c.id === short ||
      c.slug === short ||
      (c.host != null && c.host === host),
  );
}

function inviteHttps(host: string, token: string): string {
  return `https://${host}/invite/${token}`;
}

function buzzAdd(host: string, name: string): string {
  const relay = encodeURIComponent(`wss://${host}`);
  return `buzz://add-community?relay=${relay}&name=${encodeURIComponent(name)}`;
}

/**
 * Prefer a published invite token when it is still usable. Expired v1 tokens
 * on Public listings fall back to buzz://add-community (relay join). Invite-
 * only listings keep the published invite URL even if expired — converting
 * those to add-community would imply open join. v2 codes have no parseable
 * expiry and are kept as published.
 */
function mergeJoinUrl(
  existing: MarketplaceCommunity | undefined,
  host: string,
  name: string,
  access: AccessMode,
  inviteCode?: string,
): { joinUrl: string; expiredPublicFallback: boolean } {
  if (inviteCode && !shouldFallbackExpiredPublicInvite(access, inviteCode)) {
    return { joinUrl: inviteHttps(host, inviteCode), expiredPublicFallback: false };
  }

  if (shouldFallbackExpiredPublicInvite(access, inviteCode)) {
    return { joinUrl: buzzAdd(host, name), expiredPublicFallback: true };
  }

  if (existing?.joinUrl && !existing.joinUrl.startsWith("buzz://")) {
    const existingToken = inviteTokenFromJoinUrl(existing.joinUrl);
    if (shouldFallbackExpiredPublicInvite(access, existingToken)) {
      return { joinUrl: buzzAdd(host, name), expiredPublicFallback: true };
    }
    return { joinUrl: existing.joinUrl, expiredPublicFallback: false };
  }
  return { joinUrl: buzzAdd(host, name), expiredPublicFallback: false };
}

function toRecord(
  row: ResolvedCommunity,
  existing: MarketplaceCommunity | undefined,
  listedAtNow: string,
): { record: MarketplaceCommunity; expiredPublicFallback: boolean } {
  const short = marketplaceIdFromDirectorySlug(row.directorySlug);
  const host = hostFromRelayUrl(row.relayUrl);
  const name = row.name || existing?.name || short;
  const mapped = mapDirectoryCategory(row.category);
  const tags =
    existing?.tags?.length ? existing.tags : mapped ? [mapped] : [];
  const access: AccessMode =
    row.access ?? existing?.access ?? (row.inviteCode ? "public" : "invite");
  const { joinUrl, expiredPublicFallback } = mergeJoinUrl(
    existing,
    host,
    name,
    access,
    row.inviteCode,
  );

  return {
    record: {
      id: existing?.id ?? short,
      name,
      slug: existing?.slug ?? short,
      blurb:
        row.description && row.description !== existing?.blurb
          ? row.description
          : (existing?.blurb ?? row.description ?? ""),
      tags,
      access,
      joinUrl,
      host,
      listedAt: existing?.listedAt ?? listedAtNow,
      source: existing?.source ?? "external",
    },
    expiredPublicFallback,
  };
}

function recordsEqual(a: MarketplaceCommunity, b: MarketplaceCommunity): boolean {
  return JSON.stringify(stableFields(a)) === JSON.stringify(stableFields(b));
}

function stableFields(c: MarketplaceCommunity) {
  return {
    id: c.id,
    name: c.name,
    slug: c.slug,
    blurb: c.blurb,
    tags: c.tags,
    access: c.access,
    joinUrl: c.joinUrl,
    host: c.host ?? "",
    listedAt: c.listedAt,
    source: c.source ?? "",
  };
}

function sortCommunities(rows: MarketplaceCommunity[]): MarketplaceCommunity[] {
  return [...rows].sort((a, b) => a.id.localeCompare(b.id));
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const previous = readGenerated(args.outPath);
  const listedAtNow = new Date().toISOString();

  console.log(`Fetching ${DIRECTORY_ORIGIN}/communities …`);
  const listed = await fetchDirectoryListings();
  console.log(`Listed ${listed.length} communities (paginated).`);

  const skipped: string[] = [];
  const resolvedRows = await mapPool(
    listed,
    DETAIL_CONCURRENCY,
    async (row, index) => {
      if (index > 0) await sleep(DETAIL_GAP_MS);
      const url = `${DIRECTORY_ORIGIN}/communities/${row.directorySlug}`;
      try {
        const html = await fetchText(url);
        const claim = parseBuzzCommunityRelay(html);
        if (!claim) {
          skipped.push(row.directorySlug);
          return null;
        }
        const resolved: ResolvedCommunity = {
          ...row,
          relayUrl: claim.relayUrl,
          ...(claim.inviteCode ? { inviteCode: claim.inviteCode } : {}),
        };
        return resolved;
      } catch (err) {
        skipped.push(row.directorySlug);
        console.warn(
          `skip ${row.directorySlug}:`,
          err instanceof Error ? err.message : err,
        );
        return null;
      }
    },
  );

  const resolved = resolvedRows.filter((r): r is ResolvedCommunity => r != null);
  const byId = new Map(previous.map((c) => [c.id, c]));
  let added = 0;
  let updated = 0;
  let unchanged = 0;
  let expiredPublicFallback = 0;

  for (const row of resolved) {
    const host = hostFromRelayUrl(row.relayUrl);
    const existing = findExisting(row, host, previous);
    const { record: next, expiredPublicFallback: fellBack } = toRecord(
      row,
      existing,
      listedAtNow,
    );
    if (fellBack) expiredPublicFallback += 1;
    const prev = existing ? byId.get(existing.id) : undefined;
    if (!prev) {
      byId.set(next.id, next);
      added += 1;
      continue;
    }
    if (recordsEqual(prev, next)) {
      unchanged += 1;
      continue;
    }
    byId.set(next.id, next);
    updated += 1;
  }

  const nextRows = sortCommunities([...byId.values()]);
  const body = serializeGenerated(nextRows);

  console.log(
    [
      `Resolved ${resolved.length}/${listed.length} relays.`,
      `added=${added}`,
      `updated=${updated}`,
      `unchanged=${unchanged}`,
      `skipped=${skipped.length}`,
      `expiredPublicFallback=${expiredPublicFallback}`,
      `kept=${nextRows.length}`,
    ].join(" "),
  );
  if (skipped.length) {
    console.log(`Skipped (no verified relay): ${skipped.join(", ")}`);
  }

  if (args.dryRun) {
    console.log("Dry run — generated catalog not written.");
    return;
  }

  fs.mkdirSync(path.dirname(args.outPath), { recursive: true });
  fs.writeFileSync(args.outPath, body);
  console.log(`Wrote ${nextRows.length} communities → ${path.relative(ROOT, args.outPath)}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack ?? err.message : err);
  process.exitCode = 1;
});
