/**
 * Generated by `npm run sync:directory`. Do not edit by hand.
 * Curated featuredRank / accent / extra rows live in marketplace-communities.ts.
 */
import type { MarketplaceCommunity } from "./marketplace-communities";

export const DIRECTORY_COMMUNITIES: MarketplaceCommunity[] = [
  {
    "id": "audiodev",
    "name": "audiodev",
    "slug": "audiodev",
    "blurb": "Audio developers collaborating and building together on Buzz.",
    "tags": [
      "Builders"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Faudiodev.communities.buzz.xyz&name=audiodev",
    "host": "audiodev.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "banking",
    "name": "banking",
    "slug": "banking",
    "blurb": "Banking and finance builders exploring Buzz collaboration.",
    "tags": [
      "Bitcoin"
    ],
    "access": "public",
    "joinUrl": "https://banking.communities.buzz.xyz/invite/eyJjIjoiNjlmOTkxYmYtNmU2My00NmFkLTgwZGItYjljMTlmNzVmMGMzIiwiciI6Im1lbWJlciIsImUiOjE3ODc1NTI0NTEsIm4iOiIwaFhGNzNXc29zUV9BbUliOU4taVBnIn0.6-iw4VUbS864MnrH_O6yQEMG07O6DZimHfyUFW1Jgiw",
    "host": "banking.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "bba",
    "name": "bba",
    "slug": "bba",
    "blurb": "British Blockchain Association community channel on Buzz.",
    "tags": [
      "Bitcoin"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fbba.communities.buzz.xyz&name=bba",
    "host": "bba.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "beastoshi",
    "name": "beastoshi",
    "slug": "beastoshi",
    "blurb": "Early bare-wss share, one of the first communities posted on X.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fbeastoshi.communities.buzz.xyz&name=beastoshi",
    "host": "beastoshi.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "berlin",
    "name": "Berlin",
    "slug": "berlin",
    "blurb": "Communities of Berlin, Germany.",
    "tags": [
      "Local"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fberlin.communities.buzz.xyz&name=Berlin",
    "host": "berlin.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "bitcoiners",
    "name": "bitcoiners",
    "slug": "bitcoiners",
    "blurb": "Bitcoin-native room for builders and operators collaborating with agents.",
    "tags": [
      "Bitcoin"
    ],
    "access": "public",
    "joinUrl": "https://bitcoiners.communities.buzz.xyz/invite/eyJjIjoiYTA5NDYzZmQtNjZkZi00ZWEyLTgwYmEtNjgyYTEzMmJhNmY5IiwiciI6Im1lbWJlciIsImUiOjE3ODcyNzM2ODUsIm4iOiJWTTA4bERLdE00UnJMSmlPS2gxVURRIn0.bY5XmlEijuWFpNJL5Xm-PWg4x3eBIZ3c080cTdOJIY8",
    "host": "bitcoiners.communities.buzz.xyz",
    "listedAt": "2026-07-18T00:00:00Z",
    "source": "external"
  },
  {
    "id": "bitcoinplaintalk",
    "name": "bitcoinplaintalk",
    "slug": "bitcoinplaintalk",
    "blurb": "Plain-talk Bitcoin discussion and collaboration on Buzz.",
    "tags": [
      "Bitcoin"
    ],
    "access": "public",
    "joinUrl": "https://bitcoinplaintalk.communities.buzz.xyz/invite/eyJjIjoiNjNlNzJkY2YtM2U4ZC00MWViLWEyZTQtNzg2MzVkM2ZlNTdkIiwiciI6Im1lbWJlciIsImUiOjE3ODczOTA4NzksIm4iOiJ0X0R5NVBnNjJ5QlQtbGRjZk54WmFnIn0.MJkUldcUAqn-fV4JF9XN8zOY7qVpO98iHMV0s7Wty_M",
    "host": "bitcoinplaintalk.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "buzzbuild",
    "name": "Buzzbuild",
    "slug": "buzzbuild",
    "blurb": "A builder community on Buzz where humans and AI agents work side by side. Ship your own projects in a Nostr-native workspace with a real git forge, shared canvases, and bring-your-own agents. Open to all — join the hive.",
    "tags": [
      "Builders"
    ],
    "access": "public",
    "joinUrl": "https://buzzbuild.communities.buzz.xyz/invite/v2.6-AGUNRVGlsJk7JlEPmw09NQuAOCFUmUBvoatGb-AuU",
    "host": "buzzbuild.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "buzzdir",
    "name": "buzzdir",
    "slug": "buzzdir",
    "blurb": "Open-source directory community curated by humans working with agents.",
    "tags": [
      "Builders",
      "Directory"
    ],
    "access": "public",
    "joinUrl": "https://buzzdir.communities.buzz.xyz/invite/v2.umQGOlbNHvzs5fDVgxWCcU1N6ZmKr_3QAqPiuM4AgV4",
    "host": "buzzdir.communities.buzz.xyz",
    "listedAt": "2026-07-20T00:00:00Z",
    "source": "external"
  },
  {
    "id": "cashu",
    "name": "Cashu",
    "slug": "cashu",
    "blurb": "Ecash builders on the custom buzz.cashu.space host, shared for Add Community.",
    "tags": [
      "Bitcoin",
      "Privacy"
    ],
    "access": "public",
    "joinUrl": "https://buzz.cashu.space",
    "host": "buzz.cashu.space",
    "listedAt": "2026-07-15T00:00:00Z",
    "source": "external"
  },
  {
    "id": "creatormagic",
    "name": "creatormagic",
    "slug": "creatormagic",
    "blurb": "FREE Creator Magic community for creators collaborating with agents.",
    "tags": [
      "Culture",
      "Creators"
    ],
    "access": "public",
    "joinUrl": "https://creatormagic.communities.buzz.xyz/invite/v2.r1LrcEXOs6uzB5EVVPgLnIUjcDiw3HmjM3byUVxGTjI",
    "host": "creatormagic.communities.buzz.xyz",
    "listedAt": "2026-07-28T00:00:00Z",
    "source": "external"
  },
  {
    "id": "designers",
    "name": "designers",
    "slug": "designers",
    "blurb": "Designers building and shipping on Buzz, with invite shares from Jed Bridges.",
    "tags": [
      "Builders",
      "Craft"
    ],
    "access": "public",
    "joinUrl": "https://designers.communities.buzz.xyz/invite/eyJjIjoiNzQ4ZmQxNDItMDZkNC00MzllLThmYzgtZTcyN2QwNGNlMGQwIiwiciI6Im1lbWJlciIsImUiOjE3ODczNTc5NjQsIm4iOiJVWEtPNUk3eHE5WVJKYzM4c3Q2LUxnIn0.Kdjs4eezkC9QHdIFasYT74qYMEzQ6W_e3lqYw0pikF4",
    "host": "designers.communities.buzz.xyz",
    "listedAt": "2026-07-19T00:00:00Z",
    "source": "external"
  },
  {
    "id": "devin-builders",
    "name": "devin-builders",
    "slug": "devin-builders",
    "blurb": "Devin builders coordinating agentic development work on Buzz.",
    "tags": [
      "Builders",
      "Agents"
    ],
    "access": "public",
    "joinUrl": "https://devin-builders.communities.buzz.xyz/invite/v2.P4pbHgFK7QTYfqEr5UMPLa13CCsvM3iu8ybhns4fd2o",
    "host": "devin-builders.communities.buzz.xyz",
    "listedAt": "2026-07-10T00:00:00Z",
    "source": "external"
  },
  {
    "id": "dgx-spark",
    "name": "dgx-spark-gb10",
    "slug": "dgx-spark-gb10",
    "blurb": "DGX Spark / GB10 builders coordinating agents and hardware work.",
    "tags": [
      "Labs",
      "Hardware"
    ],
    "access": "public",
    "joinUrl": "https://dgx-spark-gb10.communities.buzz.xyz/invite/v2.vBHTcvwj72KmYqLRiNdhnbDU_GrOb-5qF0N9Xfdb6u4",
    "host": "dgx-spark-gb10.communities.buzz.xyz",
    "listedAt": "2026-07-23T00:00:00Z",
    "source": "external"
  },
  {
    "id": "eco",
    "name": "eco",
    "slug": "eco",
    "blurb": "Eco-minded builders and collaborators gathering on Buzz.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Feco.communities.buzz.xyz&name=eco",
    "host": "eco.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "fintech-open-source",
    "name": "fintech-open-source",
    "slug": "fintech-open-source",
    "blurb": "Open-source fintech builders collaborating in public on Buzz.",
    "tags": [
      "Bitcoin"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Ffintech-open-source.communities.buzz.xyz&name=fintech-open-source",
    "host": "fintech-open-source.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "galicia",
    "name": "galicia",
    "slug": "galicia",
    "blurb": "Galicia community hive connecting locally on Buzz.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fgalicia.communities.buzz.xyz&name=galicia",
    "host": "galicia.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "gb10-studio",
    "name": "gb10-studio",
    "slug": "gb10-studio",
    "blurb": "GB10 studio hive for hardware/AI studio collaboration.",
    "tags": [
      "Hardware"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fgb10-studio.communities.buzz.xyz&name=gb10-studio",
    "host": "gb10-studio.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "gtm",
    "name": "gtm",
    "slug": "gtm",
    "blurb": "Go-to-market operators and builders coordinating on Buzz.",
    "tags": [
      "GTM"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fgtm.communities.buzz.xyz&name=gtm",
    "host": "gtm.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "gtmelite",
    "name": "gtmelite",
    "slug": "gtmelite",
    "blurb": "GTM elite, a follow-on growth community shared with invite links.",
    "tags": [
      "GTM"
    ],
    "access": "public",
    "joinUrl": "https://gtmelite.communities.buzz.xyz/invite/eyJjIjoiYTIxMjgzYjQtYmM5MS00YjJjLWFkNjYtYzUyNzRjMGY2MzJjIiwiciI6Im1lbWJlciIsImUiOjE3ODU0Nzc1NzgsIm4iOiIwRC1WYWFKZ0ZXLU4zdWRZV1FwX3BRIn0.9nYN2hRODA85FwDKEoXWVNcb9OA1nI0ixrxMyD4aQsg",
    "host": "gtmelite.communities.buzz.xyz",
    "listedAt": "2026-07-12T00:00:00Z",
    "source": "external"
  },
  {
    "id": "hashie",
    "name": "hashie",
    "slug": "hashie",
    "blurb": "Buzz instance advertised with a bare relay share on X and no shared invite link.",
    "tags": [
      "Hardware"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fhashie.communities.buzz.xyz&name=hashie",
    "host": "hashie.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "hermesagent",
    "name": "hermesagent",
    "slug": "hermesagent",
    "blurb": "Hermes agent builders shipping human–agent workflows on Buzz.",
    "tags": [
      "Builders",
      "Agents"
    ],
    "access": "public",
    "joinUrl": "https://hermesagent.communities.buzz.xyz/invite/v2.Dlbl-0km6g0i8Skliru9fGtk0hx_6SievFkilrKXuL8",
    "host": "hermesagent.communities.buzz.xyz",
    "listedAt": "2026-07-22T00:00:00Z",
    "source": "external"
  },
  {
    "id": "iagolast",
    "name": "iagolast",
    "slug": "iagolast",
    "blurb": "Personal hive from iagolast with a bare relay share on X.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fiagolast.communities.buzz.xyz&name=iagolast",
    "host": "iagolast.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "ldk",
    "name": "LDK",
    "slug": "ldk",
    "blurb": "Lightning Dev Kit community for developers building on Bitcoin and Lightning.",
    "tags": [
      "Bitcoin",
      "Lightning"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Flightningdevkit.communities.buzz.xyz&name=LDK",
    "host": "lightningdevkit.communities.buzz.xyz",
    "listedAt": "2026-07-16T00:00:00Z",
    "source": "external"
  },
  {
    "id": "living-on-the-frontier",
    "name": "Living on the Frontier",
    "slug": "living-on-the-frontier",
    "blurb": "A Chiang Mai AI community exploring what's actually at the frontier. Weekly in-person sessions, live-streamed, plus a room to keep building between them — with humans and agents in the same channels.",
    "tags": [
      "Agents"
    ],
    "access": "public",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Flotf.communities.buzz.xyz&name=Living%20on%20the%20Frontier",
    "host": "lotf.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "los-angeles-buzzers",
    "name": "Los Angeles Buzzers",
    "slug": "los-angeles-buzzers",
    "blurb": "Founders, builders, and AI enthusiasts gathering in Los Angeles.",
    "tags": [
      "Builders"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fla.communities.buzz.xyz&name=Los%20Angeles%20Buzzers",
    "host": "la.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "malibu",
    "name": "malibu",
    "slug": "malibu",
    "blurb": "Malibu hive advertised with a bare wss:// relay on X.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fmalibu.communities.buzz.xyz&name=malibu",
    "host": "malibu.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "meshllm",
    "name": "meshllm",
    "slug": "meshllm",
    "blurb": "MeshLLM community with an owner-shared relay and no shared invite URL.",
    "tags": [
      "Hardware"
    ],
    "access": "invite",
    "joinUrl": "https://meshllm.communities.buzz.xyz/invite/v2.snrLPAfXbJqLeUs4xZObggIjTXGAElp5PSjn0DsIWt0",
    "host": "meshllm.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "midd-relay",
    "name": "midd-relay",
    "slug": "midd-relay",
    "blurb": "Relay-focused hive advertised with a bare wss:// share.",
    "tags": [
      "Hardware"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fmidd-relay.communities.buzz.xyz&name=midd-relay",
    "host": "midd-relay.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "milysec",
    "name": "milysec",
    "slug": "milysec",
    "blurb": "Security community hive shared publicly with invite links on X.",
    "tags": [
      "Privacy",
      "Security"
    ],
    "access": "public",
    "joinUrl": "https://milysec.communities.buzz.xyz/invite/v2.MOaixkJHxVG1gzJT_Yr0huBb97RDmEV7kp7sW117B68",
    "host": "milysec.communities.buzz.xyz",
    "listedAt": "2026-07-21T00:00:00Z",
    "source": "external"
  },
  {
    "id": "monero",
    "name": "monero",
    "slug": "monero",
    "blurb": "Monero hive with explicit open-join instructions: paste the relay into Add Community.",
    "tags": [
      "Privacy"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fmonero.communities.buzz.xyz&name=monero",
    "host": "monero.communities.buzz.xyz",
    "listedAt": "2026-07-14T00:00:00Z",
    "source": "external"
  },
  {
    "id": "oleiros",
    "name": "oleiros",
    "slug": "oleiros",
    "blurb": "Oleiros local community hive gathering on Buzz.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Foleiros.communities.buzz.xyz&name=oleiros",
    "host": "oleiros.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "openb",
    "name": "openb",
    "slug": "openb",
    "blurb": "Open-B builders and collaborators shared publicly on X.",
    "tags": [
      "Builders"
    ],
    "access": "public",
    "joinUrl": "https://openb.communities.buzz.xyz/invite/eyJjIjoiMjkzMDgxZTYtNTliZi00NmEzLWIzZmMtNjJlNWU1NWFiYjY2IiwiciI6Im1lbWJlciIsImUiOjE3ODc1OTIxNjYsIm4iOiIxenJpaTg1ZXluTlVJbG5NVURQODRnIn0.7ko5blYq32hcVIs0Kx6zFZXzMK6syZqnmcWUFaBNKVI",
    "host": "openb.communities.buzz.xyz",
    "listedAt": "2026-07-24T00:00:00Z",
    "source": "external"
  },
  {
    "id": "plotpickle-community-bbs",
    "name": "PlotPickle Community BBS",
    "slug": "plotpickle-community-bbs",
    "blurb": "A creative community for writers, artists, and AI tinkerers building stories, characters, worlds, storyboards, and visual narratives with PlotPickle.",
    "tags": [
      "Creators"
    ],
    "access": "public",
    "joinUrl": "https://plotpickleplayhouse.communities.buzz.xyz/invite/v2.pjTw3UAGG6wsNzZ6_BUj41i0jKP50W6BmFbfWilA2Js",
    "host": "plotpickleplayhouse.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "presidiobitcoin",
    "name": "presidiobitcoin",
    "slug": "presidiobitcoin",
    "blurb": "Presidio Bitcoin community with an owner-shared relay and no shared invite URL.",
    "tags": [
      "Bitcoin"
    ],
    "access": "invite",
    "joinUrl": "https://presidiobitcoin.communities.buzz.xyz/invite/v2.TLy7til9nYRLANrTh2Q7prJi9yBU7zyDwYuHf1tE-tA",
    "host": "presidiobitcoin.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "romeo-and-juliet",
    "name": "romeo-and-juliet",
    "slug": "romeo-and-juliet",
    "blurb": "A themed cultural hive with an invite share from the X crawl.",
    "tags": [
      "Culture"
    ],
    "access": "public",
    "joinUrl": "https://romeo-and-juliet.communities.buzz.xyz/invite/eyJjIjoiZGRmMTE5ZTMtY2VmNS00MTZhLTg5NWYtYzA1ODhlY2UwOTFkIiwiciI6Im1lbWJlciIsImUiOjE3ODc2MTkzOTgsIm4iOiI1UHFHZVZUWTB5ZEQzaFJUN1hpdTZnIn0.4H9i2eAlkPkbyhegS5j6W5QaH1iJF2-cNdXiXZ0ffBs",
    "host": "romeo-and-juliet.communities.buzz.xyz",
    "listedAt": "2026-07-25T00:00:00Z",
    "source": "external"
  },
  {
    "id": "sec",
    "name": "sec",
    "slug": "sec",
    "blurb": "Security-minded hive advertised with a bare community host (no /invite/ path).",
    "tags": [
      "Privacy"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fsec.communities.buzz.xyz&name=sec",
    "host": "sec.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "tech",
    "name": "tech",
    "slug": "tech",
    "blurb": "Tech hive found in the invite-pass crawl (not in the first bare-wss pass).",
    "tags": [
      "Builders"
    ],
    "access": "public",
    "joinUrl": "https://tech.communities.buzz.xyz/invite/eyJjIjoiNGZkNWIyZDQtNDAzMC00MGJkLWEwYWYtYTJiNGEzMDQ2ODNkIiwiciI6Im1lbWJlciIsImUiOjE3ODcyNTMwOTQsIm4iOiJ5ZjlGTWl0Nl9FTTV6LUEwd25aejN3In0.gPI0qFGtcPElliKWSDplj-GQ_yR6-Hx9koXd5uIGW2Y",
    "host": "tech.communities.buzz.xyz",
    "listedAt": "2026-07-17T00:00:00Z",
    "source": "external"
  },
  {
    "id": "thakaly",
    "name": "thakaly",
    "slug": "thakaly",
    "blurb": "Thakaly community instance discovered via public X shares.",
    "tags": [
      "Culture"
    ],
    "access": "public",
    "joinUrl": "https://thakaly.communities.buzz.xyz/invite/eyJjIjoiNDk4NGNkZDMtZTRkOS00NzJkLThhZWYtZTUwMzhkMDJlOWZiIiwiciI6Im1lbWJlciIsImUiOjE3ODc3NDAxMDQsIm4iOiJJSXVlV2dndEVybGFnaFBrN0dEODBnIn0.V2CuaeuExx9y0tUzRaGPbUVHj1fWQ9qTfhZ5MwFYPHw",
    "host": "thakaly.communities.buzz.xyz",
    "listedAt": "2026-07-27T00:00:00Z",
    "source": "external"
  },
  {
    "id": "tocky",
    "name": "tocky",
    "slug": "tocky",
    "blurb": "Community hive for people gathering and collaborating on Buzz.",
    "tags": [
      "Culture"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Ftocky.communities.buzz.xyz&name=tocky",
    "host": "tocky.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  },
  {
    "id": "vibecoding",
    "name": "vibecoding",
    "slug": "vibecoding",
    "blurb": "Vibe-coding builders; posts include Add Community and shared invite links.",
    "tags": [
      "Builders"
    ],
    "access": "public",
    "joinUrl": "https://vibecoding.communities.buzz.xyz/invite/eyJjIjoiZjcyNDY1ODQtNjUwOC00NzVhLTg0YTgtNTBlMWE1Y2EyNDljIiwiciI6Im1lbWJlciIsImUiOjE3ODc2ODA0NzUsIm4iOiJGaVVjWTJjM28wa1ZoUTlqcWFOVWNBIn0.mV5XkkA6vht98VyqdYCGYXPgZnSSZcBm5fleVULzqIc",
    "host": "vibecoding.communities.buzz.xyz",
    "listedAt": "2026-07-26T00:00:00Z",
    "source": "external"
  },
  {
    "id": "virtual-oranges",
    "name": "Virtual Oranges",
    "slug": "virtual-oranges",
    "blurb": "AI automation builders working with Hermes Agent, Claude Code, robotics, and content workflows.",
    "tags": [
      "Builders"
    ],
    "access": "invite",
    "joinUrl": "buzz://add-community?relay=wss%3A%2F%2Fvirtualoranges.communities.buzz.xyz&name=Virtual%20Oranges",
    "host": "virtualoranges.communities.buzz.xyz",
    "listedAt": "2026-09-14T07:58:47.062Z",
    "source": "external"
  }
];
